# Generated by Django 3.2.10 on 2022-07-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticketdatatable',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
